import { BasicLayoutProps } from "@ant-design/pro-layout";

const layout: BasicLayoutProps = {
  title: "React Awesome",
  logo: "/assets/react.svg",
  pure: false,
  loading: true,
  // menuHeaderRender,
  // onMenuHeaderClick,
  // contentStyle,
  layout: "side",
  contentWidth: "Fluid",
  navTheme: "dark",
  fixedHeader: false,
  fixSiderbar: true,
  breakpoint: "lg",
  menu: { locale: true },
  // iconfontUrl,
  locale: "zh-CN"
  // siderWidth: 256,
  // onCollapse,
  // onPageChange,
  // headerRender,
  // headerTitleRender,
  // headerContentRender,
  // rightContentRender,
  // collapsedButtonRender,
  // footerRender,
  // pageTitleRender,
  // menuRender,
  // postMenuData,
  // menuItemRender,
  // subMenuItemRender,
  // menuDataRender,
  // breadcrumbRender,
  // route,
  // disableMobile,
  // links,
  // menuProps,
};

export default layout;
